enum Getters {
  TETROMINO_POSITION = "TETROMINO_POSITION",
  TETROMINO_SHAPE = "TETROMINO_SHAPE",
  TETROMINO_COLOR = "TETROMINO_COLOR",
  TETROMINO = "TETROMINO",

  GRID = "GRID",
  GRID_CELL = "GRID_CELL",

  GAME_LEVEL = "GAME_LEVEL",
  GAME_LEVEL_COUNTDOWN = "GAME_LEVEL_COUNTDOWN",
  GAME_SCORE = "GAME_SCORE",
  GAME_IS_RUNNING = "GAME_IS_RUNNING",
  GAME_IS_OVER = "GAME_IS_OVER",
  GAME_IS_PAUSED = "GAME_IS_PAUSED",
  GAME_HAS_BEGUN = "GAME_HAS_BEGUN",
}

export default Getters;
